delete from survey_to_question;
delete from question;
delete from survey_to_tag;
delete from survey_to_participant;
delete from participant;
delete from survey;
delete from instructor;
delete from user;
delete from tag;
