insert into tag values (1, 'name', 'COS 140 001'), (2, 'description', 'Description'), (3, 'welcometext', 'Welcome to the survey.'), (4, 'endtext', 'Thank you for completing this survey.'), (5, 'email_invite', 'Dear {FIRSTNAME},<br/><br/>you have been invited to participate in a survey.<br/><br/>Click here to do the survey:<br/>{SURVEYURL}<br/><br/>Please enter the token {TOKEN} to access the survey.'), (6, 'email_remind', 'Dear {FIRSTNAME},<br/><br/>we wish to remind you to participate in a survey.<br/><br/>Click here to do the survey:<br/>{SURVEYURL}<br/><br/>Please enter the token {TOKEN} to access the survey.'), (7, 'email_register', 'Email register text'), (8, 'email_confirm', 'Dear {FIRSTNAME},<br /><br />this email is to confirm that you have completed the survey titled {SURVEYNAME} and your response has been saved. Thank you for participating.'), (9, 'startdate', '2050-01-01'), (10, 'expires', '2050-01-02'), (11, 'reminderTime', '12:00'), (12, 'name', 'COS 250 001'), (13, 'description', 'De'), (14, 'email_invite', 'Ei text'), (15, 'email_remind', 'Eremind text'), (16, 'email_register', 'Er text'), (17, 'email_confirm', 'Ec text');
insert into instructor values (1, 'Roy Turner', 'roy.turner@maine.edu'), (2, 'Torsten Hahmann', 'torsten.hahmann@maine.edu');
insert into user values (1, 'Roy Turner', 'roy.turner@maine.edu'), (2, 'Torsten Hahmann', 'torsten.hahmann@maine.edu');
insert into survey values (1, 'example.com', 1, 1), (2, 'example.com', 2, 2);
insert into participant values (1, 'Example Person', 'jovon.craig@maine.edu'), (2, 'Example2 Person', 'teachingevaluationstest@gmail.com'), (3, 'Tom Guo', 'tg@gmail.com');
insert into survey_to_participant values (1, 1), (1, 2), (2, 3);
insert into survey_to_tag values (1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (2, 12), (2, 13), (2, 14), (2, 15), (2, 16), (2, 17), (2, 3), (2, 4), (2, 9), (2, 10), (2, 11);
insert into question values (1, 'Help text', 1, 'The Instructor', '5', 'Question?'), (2, 'Help text', 1, 'The Instructor', '5', 'Question 2?'), (3, 'Help text', 0, 'The Instructor', 'Y', 'Question 3?'), (4, 'Help text', 0, 'The Instructor', 'L', 'Question 2?');
insert into survey_to_question values (1, 1), (1, 2), (1, 3), (2, 1), (2, 4);
