# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Course(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, name: str=None, addresses: List[str]=None):  # noqa: E501
        """Course - a model defined in Swagger

        :param id: The id of this Course.  # noqa: E501
        :type id: str
        :param name: The name of this Course.  # noqa: E501
        :type name: str
        :param addresses: The addresses of this Course.  # noqa: E501
        :type addresses: List[str]
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'addresses': List[str]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'addresses': 'addresses'
        }

        self._id = id
        self._name = name
        self._addresses = addresses

    @classmethod
    def from_dict(cls, dikt) -> 'Course':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Course of this Course.  # noqa: E501
        :rtype: Course
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Course.


        :return: The id of this Course.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Course.


        :param id: The id of this Course.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Course.


        :return: The name of this Course.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Course.


        :param name: The name of this Course.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def addresses(self) -> List[str]:
        """Gets the addresses of this Course.


        :return: The addresses of this Course.
        :rtype: List[str]
        """
        return self._addresses

    @addresses.setter
    def addresses(self, addresses: List[str]):
        """Sets the addresses of this Course.


        :param addresses: The addresses of this Course.
        :type addresses: List[str]
        """

        self._addresses = addresses
