# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Course(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, name: str=None, copy: bool=None):  # noqa: E501
        """Course - a model defined in Swagger

        :param name: The name of this Course.  # noqa: E501
        :type name: str
        :param copy: The copy of this Course.  # noqa: E501
        :type copy: bool
        """
        self.swagger_types = {
            'name': str,
            'copy': bool
        }

        self.attribute_map = {
            'name': 'name',
            'copy': 'copy'
        }

        self._name = name
        self._copy = copy

    @classmethod
    def from_dict(cls, dikt) -> 'Course':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The course of this Course.  # noqa: E501
        :rtype: Course
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Course.


        :return: The name of this Course.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Course.


        :param name: The name of this Course.
        :type name: str
        """

        self._name = name

    @property
    def copy(self) -> bool:
        """Gets the copy of this Course.

        copy info from a course of the same name  # noqa: E501

        :return: The copy of this Course.
        :rtype: bool
        """
        return self._copy

    @copy.setter
    def copy(self, copy: bool):
        """Sets the copy of this Course.

        copy info from a course of the same name  # noqa: E501

        :param copy: The copy of this Course.
        :type copy: bool
        """

        self._copy = copy
