# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.template_questions import TemplateQuestions  # noqa: F401,E501
from swagger_server import util


class Template(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: str=None, questions: List[TemplateQuestions]=None):  # noqa: E501
        """Template - a model defined in Swagger

        :param id: The id of this Template.  # noqa: E501
        :type id: str
        :param questions: The questions of this Template.  # noqa: E501
        :type questions: List[TemplateQuestions]
        """
        self.swagger_types = {
            'id': str,
            'questions': List[TemplateQuestions]
        }

        self.attribute_map = {
            'id': 'id',
            'questions': 'questions'
        }

        self._id = id
        self._questions = questions

    @classmethod
    def from_dict(cls, dikt) -> 'Template':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Template of this Template.  # noqa: E501
        :rtype: Template
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Template.


        :return: The id of this Template.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Template.


        :param id: The id of this Template.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def questions(self) -> List[TemplateQuestions]:
        """Gets the questions of this Template.


        :return: The questions of this Template.
        :rtype: List[TemplateQuestions]
        """
        return self._questions

    @questions.setter
    def questions(self, questions: List[TemplateQuestions]):
        """Sets the questions of this Template.


        :param questions: The questions of this Template.
        :type questions: List[TemplateQuestions]
        """
        if questions is None:
            raise ValueError("Invalid value for `questions`, must not be `None`")  # noqa: E501

        self._questions = questions
