---
swagger: "2.0"
info:
  description: "This is an API used for connecting the front end to the backend of\
    \ our software."
  version: "1.0.0"
  title: "Project Eval API"
  contact:
    email: "contact@teachingevaluations.org"
  license:
    name: "GPL 2.0"
    url: "https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html"
host: "virtserver.swaggerhub.com"
basePath: "/teameval/Eval/1.0.0"
tags:
- name: "admins"
  description: "Operations available to administrators"
- name: "teachers"
  description: "Operations available to teachers"
schemes:
- "https"
paths:
  /login:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "retrieves a token for a certain authentication key"
      operationId: "login_get"
      parameters:
      - name: "key"
        in: "query"
        description: "an authentication key"
        required: true
        type: "string"
      responses:
        200:
          description: "the authentication token"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /create_user:
    post:
      tags:
      - "teachers"
      - "admins"
      summary: "adds a user to the database"
      operationId: "create_user_post"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /surveys:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "retreives a list of all courses"
      operationId: "surveys_get"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "the ID for a teacher/administrator"
        required: true
        type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Course"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /survey:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "retreives the info for a specified course"
      operationId: "survey_get"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "the name for a course"
        required: true
        type: "string"
      responses:
        200:
          description: "course info matching criteria"
          schema:
            $ref: "#/definitions/Course"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
    put:
      tags:
      - "teachers"
      - "admins"
      summary: "updates the info for a specified course"
      operationId: "survey_put"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
    delete:
      tags:
      - "teachers"
      - "admins"
      summary: "deletes a specified course"
      operationId: "survey_delete"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "the name for a course"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            type: "string"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /publish:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "publishes a survey with the specified name"
      operationId: "publish_get"
      produces:
      - "application/json"
      parameters:
      - name: "name"
        in: "query"
        description: "the name for a survey"
        required: true
        type: "string"
      responses:
        200:
          description: "success message"
          schema:
            $ref: "#/definitions/Course"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
  /results:
    get:
      tags:
      - "teachers"
      - "admins"
      summary: "retreives a list of survey results, optionally for a specified instructor"
      operationId: "results_get"
      produces:
      - "application/json"
      parameters:
      - name: "instructor"
        in: "query"
        description: "the instructor to which the results pertain"
        type: "string"
      responses:
        200:
          description: "survey results found"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Result"
        400:
          description: "bad input parameter"
      x-swagger-router-controller: "swagger_server.controllers.teachers_controller"
definitions:
  Course:
    type: "object"
    required:
    - "id"
    - "name"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "1"
      name:
        type: "string"
        example: "COS 397"
      addresses:
        type: "array"
        example:
        - "stanley.small@maine.edu"
        - "jovon.craig@maine.edu"
        items:
          type: "string"
    example:
      addresses:
      - "stanley.small@maine.edu"
      - "jovon.craig@maine.edu"
      name: "COS 397"
      id: "1"
  Result:
    type: "object"
    required:
    - "course"
    - "question id"
    properties:
      course:
        type: "string"
        example: "COS 397"
      question id:
        type: "string"
        format: "uuid"
        example: "12"
    example:
      course: "COS 397"
      question id: "12"
