-- MySQL Script generated by MySQL Workbench
-- Fri 09 Nov 2018 02:02:55 PM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`instructor` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `e-mail` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(50) NULL,
  `instructor_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_survey_instructor1_idx` (`instructor_ID` ASC),
  CONSTRAINT `fk_survey_instructor1`
    FOREIGN KEY (`instructor_ID`)
    REFERENCES `mydb`.`instructor` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participant` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NULL,
  `address` VARCHAR(50) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey_to_participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_to_participant` (
  `survey_ID` INT NOT NULL,
  `participant_ID` INT NOT NULL,
  PRIMARY KEY (`survey_ID`, `participant_ID`),
  INDEX `fk_survey_has_participant_participant1_idx` (`participant_ID` ASC),
  INDEX `fk_survey_has_participant_survey1_idx` (`survey_ID` ASC),
  CONSTRAINT `fk_survey_to_participant_survey1`
    FOREIGN KEY (`survey_ID`)
    REFERENCES `mydb`.`survey` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_to_participant_participant1`
    FOREIGN KEY (`participant_ID`)
    REFERENCES `mydb`.`participant` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`question` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `helpText` VARCHAR(50) NULL,
  `mandatory` BIT NULL,
  `group` VARCHAR(50) NULL,
  `type` VARCHAR(50) NULL,
  `text` VARCHAR(150) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey_to_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_to_question` (
  `survey_ID` INT NOT NULL,
  `question_ID` INT NOT NULL,
  PRIMARY KEY (`survey_ID`, `question_ID`),
  INDEX `fk_survey_has_question_question1_idx` (`question_ID` ASC),
  INDEX `fk_survey_has_question_survey1_idx` (`survey_ID` ASC),
  CONSTRAINT `fk_survey_to_question_survey1`
    FOREIGN KEY (`survey_ID`)
    REFERENCES `mydb`.`survey` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_to_question_question1`
    FOREIGN KEY (`question_ID`)
    REFERENCES `mydb`.`question` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`response`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`response` (
  `ID` INT NOT NULL,
  `text` VARCHAR(150) NULL,
  `survey_ID` INT NOT NULL,
  `question_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `survey_ID`, `question_ID`),
  INDEX `fk_response_survey_to_question1_idx` (`survey_ID` ASC, `question_ID` ASC),
  CONSTRAINT `fk_response_survey_to_question1`
    FOREIGN KEY (`survey_ID` , `question_ID`)
    REFERENCES `mydb`.`survey_to_question` (`survey_ID` , `question_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tag` (
  `ID` INT NOT NULL,
  `type` VARCHAR(50) NULL,
  `value` VARCHAR(500) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`survey_to_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`survey_to_tag` (
  `survey_ID` INT NOT NULL,
  `tag_ID` INT NOT NULL,
  PRIMARY KEY (`survey_ID`, `tag_ID`),
  INDEX `fk_survey_to_tag_tag1_idx` (`tag_ID` ASC),
  INDEX `fk_survey_to_tag_survey1_idx` (`survey_ID` ASC),
  CONSTRAINT `fk_survey_has_tag_survey1`
    FOREIGN KEY (`survey_ID`)
    REFERENCES `mydb`.`survey` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_survey_has_tag_tag1`
    FOREIGN KEY (`tag_ID`)
    REFERENCES `mydb`.`tag` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
